modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/florensie/swimmies/issues"
license = "MIT"

[[mods]]
modId = "swimmies"
version = "${version}"
displayName = "Swimmies"
authors = "Florens"
description = '''
Minecraft mod that allows enabling swimming behaviour without being in water
'''
logoFile = "assets/swimmies/icon.png"

[[dependencies.swimmies]]
modId = "forge"
mandatory = true
versionRange = "[32.0.75,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.swimmies]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,)"
ordering = "NONE"
side = "BOTH"
