modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/florensie/effectful/issues"
license = "MIT"

[[mods]]
modId = "effectful"
version = "${version}"
displayName = "Effectful"
authors = "Florens"
description = '''
Library mod that provides increased control over vanilla effects and abilities
'''
logoFile = "assets/effectful/icon.png"

[[dependencies.effectful]]
modId = "forge"
mandatory = true
versionRange = "[32.0.75,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.effectful]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,)"
ordering = "NONE"
side = "BOTH"
