modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/florensie/expandability/issues"
license = "MIT"

[[mods]]
modId = "expandability"
version = "${version}"
displayName = "ExpandAbility"
authors = "Florens"
description = '''
Library mod that provides increased control over vanilla abilities
'''
logoFile = "assets/expandability/icon.png"

[[dependencies.expandability]]
modId = "forge"
mandatory = true
versionRange = "[32.0.75,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandability]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,)"
ordering = "NONE"
side = "BOTH"
