modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/florensie/expandability/issues"
license = "MIT"

[[mods]]
modId = "expandability"
version = "${version}"
displayName = "ExpandAbility"
authors = "Florens"
description = '''
Library mod that provides increased control over vanilla abilities
'''
logoFile = "icon.png"

[[dependencies.expandability]]
modId = "forge"
mandatory = true
versionRange = "[37.0.59,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandability]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"
