modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"

[[mods]]
modId = "examplemod"
# The version number of the mod - unlike in the Forge MDK,
# we'll use the processResources task to replace this for us
version = "${version}"
displayName = "Example Mod"
description = '''
This is a very cool mod that does... things.

...and stuff.

Have I reached 280 characters yet?
'''

# An (optional) dependency for your mod. Though technically not required,
# it's always helpful to add these to stop your mod from loading when something is missing
# rather than erroring out later
[[dependencies.examplemod]]
modId = "forge"
mandatory = true # do you **need** this mod to be able to launch?
# A version range using interval notation.
# Brackets mean "inclusive" bounds, while parentheses mean "exclusive".
versionRange = "[41,)" # This essentially means any forge >= 41
ordering = "NONE" # Use this if you want your mod to be loaded specifically BEFORE or AFTER another mod
side = "BOTH" # Specify where this mod is required: can be BOTH, CLIENT or SERVER

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true

versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
