modLoader="javafml"
loaderVersion="[42,)"
license="MIT"

[[mods]]
modId="expandabilitytest"
version="${file.jarVersion}"
displayName="Expandability Forge Testing"
authors="Florens Pauwels"
description='''
A mod for testing development and testing of ExpandAbility for Forge.
'''

[[dependencies.expandabilitytest]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.expandabilitytest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"
