modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"

[[mods]]
modId = "effectful-test"
version = "${version}"
displayName = "Effectful Test"
authors = "Florens"
description = '''
Testmod for Effectful
'''

[[dependencies.effectful-test]]
modId = "effectful"
mandatory = true
ordering = "NONE"
side = "BOTH"
