modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"

[[mods]]
modId = "expandability-test"
version = "${version}"
displayName = "ExpandAbility Test"
authors = "Florens"
description = '''
Testmod for ExpandAbility
'''

[[dependencies.expandability-test]]
modId = "expandability"
mandatory = true
ordering = "NONE"
side = "BOTH"
